-- Harvestia App NASA Data Quiz
-- Questions specifically for the NASA data features available in Harvestia app

-- Create Harvestia NASA Features Quiz
insert into public.quizzes (
   id,
   title,
   difficulty,
   nasa_topic,
   questions_count,
   attempts_allowed
) values ( 'harvestia-nasa-features',
           'Harvestia App এ NASA Data ব্যবহার করুন',
           'Easy',
           'Harvestia Features',
           0,
           5 );

-- Harvestia app specific NASA data questions
insert into public.quiz_questions (
   quiz_id,
   question,
   options,
   correct_answer,
   explanation,
   nasa_data_reference
) values ( 'harvestia-nasa-features',
           'Harvestia app এ Dashboard এ আপনি কোন NASA data দেখতে পাবেন?',
           '["শুধু weather forecast", "NDVI chart, soil moisture, precipitation data", "শুধু temperature", "কোনো NASA data নেই"]'
           ,
           'NDVI chart, soil moisture, precipitation data',
           'Harvestia Dashboard এ NASA MODIS থেকে NDVI chart, SMAP থেকে soil moisture, এবং GPM থেকে precipitation data সব একসাথে দেখানো হয়।'
           ,
           '{"harvestia_feature": "Dashboard NASA Integration", "data_sources": ["MODIS_NDVI", "SMAP_soil_moisture", "GPM_precipitation"]}'
           ),( 'harvestia-nasa-features',
                                                                                                                                            'Agricultural Simulation page এ NASA data কীভাবে কাজ করে?'
                                                                                                                                            ,
                                                                                                                                            '["কোনো NASA data ব্যবহার হয় না", "আপনার location select করলে সেই এলাকার real NASA data দিয়ে simulation চলে", "শুধু fake data ব্যবহার হয়", "শুধু historical data"]'
                                                                                                                                            ,
                                                                                                                                            'আপনার location select করলে সেই এলাকার real NASA data দিয়ে simulation চলে'
                                                                                                                                            ,
                                                                                                                                            'Harvestia Simulation এ আপনি map এ যে location click করবেন, সেই এলাকার actual NASA SMAP soil moisture এবং MODIS vegetation data দিয়ে realistic farming simulation চালানো হয়।'
                                                                                                                                            ,
                                                                                                                                            '{"harvestia_feature": "Real-time NASA Data Integration", "simulation_inputs": ["location_specific_SMAP", "MODIS_vegetation_health"]}'
                                                                                                                                            )
                                                                                                                                            ,
                                                                                                                                            (
                                                                                                                                            'harvestia-nasa-features'
                                                                                                                                            ,
                                                                                                                                                                                                                                                                                   'Harvestia app এর Weather section এ কোন NASA datasets এর তথ্য পাবেন?'
                                                                                                                                                                                                                                                                                   ,
                                                                                                                                                                                                                                                                                   '["শুধু local weather station data", "NASA POWER meteorological data + GPM precipitation", "শুধু temperature data", "কোনো NASA data নেই"]'
                                                                                                                                                                                                                                                                                   ,
                                                                                                                                                                                                                                                                                   'NASA POWER meteorological data + GPM precipitation'
                                                                                                                                                                                                                                                                                   ,
                                                                                                                                                                                                                                                                                   'Weather section এ NASA POWER থেকে temperature, humidity, wind speed, solar radiation এবং NASA GPM থেকে precipitation data একসাথে দেখানো হয়।'
                                                                                                                                                                                                                                                                                   ,
                                                                                                                                                                                                                                                                                   '{"harvestia_weather": "NASA POWER + GPM Integration", "parameters": ["T2M_temperature", "RH2M_humidity", "WS2M_wind", "ALLSKY_SFC_SW_DWN_solar", "GPM_precipitation"]}'
                                                                                                                                                                                                                                                                                   )
                                                                                                                                                                                                                                                                                   ,
                                                                                                                                                                                                                                                                                   (
                                                                                                                                                                                                                                                                                   'harvestia-nasa-features'
                                                                                                                                                                                                                                                                                   ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Quick Actions এ "Analytics" button এ click করলে কী দেখতে পাবেন?'
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            '["শুধু local data", "NASA MODIS থেকে আপনার এলাকার NDVI trend এবং vegetation health analysis", "কোনো data নেই", "শুধু historical records"]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            'NASA MODIS থেকে আপনার এলাকার NDVI trend এবং vegetation health analysis'
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Quick Actions এর Analytics এ NASA MODIS satellite থেকে আপনার location এর NDVI values, trend analysis, এবং crop health assessment দেখানো হয় real-time।'
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            '{"harvestia_analytics": "Real-time NDVI Analysis", "data_processing": "MODIS_time_series_analysis", "outputs": ["NDVI_trends", "vegetation_health_score"]}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            (
                                                                                                                                                                                                                                                                                                                                                                                                                                                            'harvestia-nasa-features'
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'Harvestia app কীভাবে আপনার location detect করে NASA data আনে?'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         '["manual input only", "Browser geolocation API + NASA data services", "শুধু IP address দিয়ে", "location detect করে না"]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'Browser geolocation API + NASA data services'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'Harvestia app আপনার browser এর geolocation API দিয়ে GPS coordinates নেয়, তারপর সেই lat/lon দিয়ে NASA services থেকে location-specific data fetch করে।'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         '{"location_service": "GPS + NASA Integration", "process": "geolocation_API → NASA_data_fetch", "accuracy": "location_specific"}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ;

-- Create Real NASA Data Application Quiz
insert into public.quizzes (
   id,
   title,
   difficulty,
   nasa_topic,
   questions_count,
   attempts_allowed
) values ( 'real-nasa-application',
           'বাস্তব NASA Data প্রয়োগ',
           'Medium',
           'Practical Implementation',
           0,
           3 );

-- Real application scenarios using Harvestia's NASA data
insert into public.quiz_questions (
   quiz_id,
   question,
   options,
   correct_answer,
   explanation,
   nasa_data_reference
) values ( 'real-nasa-application',
           'আপনার ধানের জমির NDVI value ০.৩ দেখাচ্ছে। এর মানে কী এবং কী করবেন?',
           '["খুবই ভালো, কিছু করার দরকার নেই", "খারাপ vegetation health, সেচ/সার দিয়ে দেখুন", "normal value", "NDVI বুঝি না"]'
           ,
           'খারাপ vegetation health, সেচ/সার দিয়ে দেখুন',
           'NDVI 0.3 মানে vegetation health খারাপ। সুস্থ ধানের NDVI থাকে 0.6-0.8। কম NDVI মানে water stress বা nutrient deficiency হতে পারে।'
           ,
           '{"crop": "rice", "NDVI_threshold": "healthy: 0.6-0.8, poor: <0.4", "action": "irrigation_fertilization"}' ),( 'real-nasa-application'
           ,
                                                                                                                        'NASA GPM data দেখাচ্ছে আগামী ২ দিনে ২০mm বৃষ্টি। আপনার কী করা উচিত?'
                                                                                                                        ,
                                                                                                                        '["যা ইচ্ছে তাই করি", "সার/কীটনাশক spray postpone করি, irrigation বন্ধ রাখি", "আরো সেচ দিই", "কিছুই করি না"]'
                                                                                                                        ,
                                                                                                                        'সার/কীটনাশক spray postpone করি, irrigation বন্ধ রাখি'
                                                                                                                        ,
                                                                                                                        '২০mm বৃষ্টি যথেষ্ট। বৃষ্টির আগে সার দিলে ধুয়ে যাবে, spray করলে কাজ করবে না। বৃষ্টির পর করাই ভালো।'
                                                                                                                        ,
                                                                                                                        '{"precipitation_forecast": "20mm", "farm_decisions": ["postpone_fertilizer", "skip_irrigation", "delay_pesticide"], "timing": "weather_based_planning"}'
                                                                                                                        ),( 'real-nasa-application'
                                                                                                                        ,
                                                                                                                                                                                                                                                                                  'SMAP soil moisture দেখাচ্ছে ১৫% আর আপনার এলাকায় ৩ দিন ধরে বৃষ্টি নেই। কী করবেন?'
                                                                                                                                                                                                                                                                                  ,
                                                                                                                                                                                                                                                                                  '["কিছু করবো না", "emergency irrigation শুরু করবো", "আরো wait করবো", "soil moisture বুঝি না"]'
                                                                                                                                                                                                                                                                                  ,
                                                                                                                                                                                                                                                                                  'emergency irrigation শুরু করবো'
                                                                                                                                                                                                                                                                                  ,
                                                                                                                                                                                                                                                                                  '১৫% soil moisture খুবই কম (ideal হলো ২৫-৩৫%)। ৩ দিন বৃষ্টি নেই মানে আরো কমবে। তাড়াতাড়ি সেচ দিতে হবে নাহলে ফসল মারা যাবে।'
                                                                                                                                                                                                                                                                                  ,
                                                                                                                                                                                                                                                                                  '{"soil_moisture_critical": "15%", "ideal_range": "25-35%", "action": "immediate_irrigation", "risk": "crop_stress"}'
                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                  ,
                                                                                                                                                                                                                                                                                  (
                                                                                                                                                                                                                                                                                  'real-nasa-application'
                                                                                                                                                                                                                                                                                  ,
                                                                                                                                                                                                                                                                                                                                                                                                        'NASA POWER data দেখাচ্ছে আজকের solar radiation 6 MJ/m²/day। এটা আপনার ফসলের জন্য কী অর্থ?'
                                                                                                                                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                                                                                                                                        '["কম sunlight, photosynthesis কম হবে", "perfect sunlight", "বেশি sunlight, ক্ষতিকর", "solar radiation বুঝি না"]'
                                                                                                                                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                                                                                                                                        'কম sunlight, photosynthesis কম হবে'
                                                                                                                                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                                                                                                                                        '৬ MJ/m²/day solar radiation কম (normal হলো ১৫-২৫)। কম সূর্যালোক মানে photosynthesis কম, growth slow। মেঘলা আবহাওয়ায় এমন হয়।'
                                                                                                                                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                                                                                                                                        '{"solar_radiation": "6 MJ/m²/day", "normal_range": "15-25 MJ/m²/day", "impact": "reduced_photosynthesis", "adaptation": "extend_growing_period"}'
                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                                                                                                                                        (
                                                                                                                                                                                                                                                                                                                                                                                                        'real-nasa-application'
                                                                                                                                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'Harvestia Dashboard এ দেখলেন NDVI trend গত ২ সপ্তাহ ধরে কমছে। সম্ভাব্য কারণ কী?'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '["কোনো সমস্যা নেই", "drought stress, pest attack, বা disease হতে পারে", "এটা normal", "NDVI trend বুঝি না"]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'drought stress, pest attack, বা disease হতে পারে'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'NDVI continuously decrease মানে vegetation health খারাপ হচ্ছে। কারণ হতে পারে: পানির অভাব, পোকার আক্রমণ, রোগ, বা nutrient deficiency।'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '{"trend_analysis": "declining_NDVI_2weeks", "possible_causes": ["water_stress", "pest_attack", "disease", "nutrient_deficiency"], "investigation_needed": true}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ;

-- Create NASA Data Interpretation Quiz  
insert into public.quizzes (
   id,
   title,
   difficulty,
   nasa_topic,
   questions_count,
   attempts_allowed
) values ( 'nasa-data-interpretation',
           'NASA Data সঠিকভাবে বুঝুন',
           'Hard',
           'Data Analysis',
           0,
           3 );

-- NASA data interpretation questions
insert into public.quiz_questions (
   quiz_id,
   question,
   options,
   correct_answer,
   explanation,
   nasa_data_reference
) values ( 'nasa-data-interpretation',
           'আপনার জমির NDVI map এ green, yellow, red colors দেখাচ্ছে। এর সঠিক ব্যাখ্যা কী?',
           '["সব জায়গায় সমান ভালো", "Green=healthy vegetation, Yellow=moderate health, Red=poor/stressed vegetation", "রঙের কোনো মানে নেই", "শুধু decoration"]'
           ,
           'Green=healthy vegetation, Yellow=moderate health, Red=poor/stressed vegetation',
           'NDVI color map এ: সবুজ = সুস্থ গাছপালা (NDVI >0.6), হলুদ = মাঝারি (0.3-0.6), লাল = খারাপ/stressed (<0.3)। এতে জমির বিভিন্ন অংশের অবস্থা বুঝা যায়।'
           ,
           '{"color_coding": {"green": ">0.6_healthy", "yellow": "0.3-0.6_moderate", "red": "<0.3_stressed"}, "application": "precision_farming_zones"}'
           ),( 'nasa-data-interpretation',
                                                                                                                                                         'NASA POWER থেকে Relative Humidity ৯০% দেখাচ্ছে। এই high humidity তে কী সমস্যা হতে পারে?'
                                                                                                                                                         ,
                                                                                                                                                         '["কোনো সমস্যা নেই", "Fungal disease এর risk বেড়ে যায়", "ফসল খুব ভালো হবে", "humidity এর কোনো প্রভাব নেই"]'
                                                                                                                                                         ,
                                                                                                                                                         'Fungal disease এর risk বেড়ে যায়'
                                                                                                                                                         ,
                                                                                                                                                         '৯০% Relative Humidity খুবই বেশি। High humidity তে fungal spores বেশি grow করে, তাই blast, blight এসব disease এর সম্ভাবনা বাড়ে। Preventive fungicide spray করা লাগতে পারে।'
                                                                                                                                                         ,
                                                                                                                                                         '{"humidity_threshold": "90%_very_high", "disease_risk": "fungal_infections", "prevention": "fungicide_application", "crops_affected": "rice_wheat_vegetables"}'
                                                                                                                                                         )
                                                                                                                                                         ,
                                                                                                                                                         (
                                                                                                                                                         'nasa-data-interpretation'
                                                                                                                                                         ,
                                                                                                                                                                                                                                                                                                                          'GPM precipitation data ৫ দিন ধরে 0mm দেখাচ্ছে, কিন্তু SMAP soil moisture এখনো 30%। এর মানে কী?'
                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                          '["data ভুল", "মাটিতে আগের পানি আছে, কিন্তু শীঘ্রই irrigation লাগবে", "কোনো সেচ লাগবে না", "বুঝতে পারছি না"]'
                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                          'মাটিতে আগের পানি আছে, কিন্তু শীঘ্রই irrigation লাগবে'
                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                          '৫ দিন বৃষ্টি নেই কিন্তু soil moisture এখনো ৩০% মানে আগের বৃষ্টির পানি মাটিতে আছে। তবে evapotranspiration এ এটা কমতে থাকবে, তাই monitoring করে irrigation এর জন্য ready থাকতে হবে।'
                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                          '{"scenario": "no_rain_5days_but_adequate_moisture", "interpretation": "residual_moisture_depleting", "action": "monitor_and_prepare_irrigation"}'
                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                          (
                                                                                                                                                                                                                                                                                                                          'nasa-data-interpretation'
                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'Winter season এ আপনার গমের জমির NDVI value 0.4। এটা কি concern এর বিষয়?'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             '["হ্যাঁ, খুবই খারাপ", "না, winter এ গমের জন্য এটা normal", "বুঝতে পারছি না", "season এর কোনো effect নেই"]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'না, winter এ গমের জন্য এটা normal'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'Winter season এ গমের growth slow থাকে, তাই NDVI 0.4-0.5 normal। Spring এ যখন active growth শুরু হবে তখন NDVI বাড়বে 0.7+ এ। Season অনুযায়ী NDVI interpret করতে হয়।'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             '{"seasonal_variation": "winter_wheat_NDVI", "normal_range": "0.4-0.5", "peak_season": "spring_0.7+", "interpretation": "season_adjusted_analysis"}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'nasa-data-interpretation'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'একই দিনে NASA data দেখাচ্ছে: NDVI=0.8, Soil Moisture=40%, Temperature=35°C। সার্বিক অবস্থা কী?'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '["সব perfect", "NDVI ভালো কিন্তু high temperature তে heat stress হতে পারে", "সব খারাপ", "শুধু temperature দেখলেই হবে"]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'NDVI ভালো কিন্তু high temperature তে heat stress হতে পারে'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'NDVI 0.8 = excellent vegetation, Soil moisture 40% = adequate। কিন্তু 35°C temperature বেশি, heat stress এর risk আছে। Extra irrigation বা shade দিয়ে temperature stress কমাতে হবে।'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '{"multi_parameter_analysis": {"NDVI": "excellent_0.8", "soil_moisture": "adequate_40%", "temperature": "stress_level_35C"}, "management": "heat_stress_mitigation"}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ;

-- Update question counts for all new quizzes
update public.quizzes
   set
   questions_count = (
      select count(*)
        from public.quiz_questions
       where quiz_id = 'harvestia-nasa-features'
   )
 where id = 'harvestia-nasa-features';

update public.quizzes
   set
   questions_count = (
      select count(*)
        from public.quiz_questions
       where quiz_id = 'real-nasa-application'
   )
 where id = 'real-nasa-application';

update public.quizzes
   set
   questions_count = (
      select count(*)
        from public.quiz_questions
       where quiz_id = 'nasa-data-interpretation'
   )
 where id = 'nasa-data-interpretation';

-- Final summary
select 'Harvestia NASA Data Quizzes Created Successfully!' as result,
       (
          select count(*)
            from public.quizzes
           where id like '%nasa%'
              or id like '%harvestia%'
       ) as app_related_quizzes,
       (
          select count(*)
            from public.quiz_questions
           where quiz_id like '%nasa%'
              or quiz_id like '%harvestia%'
       ) as total_questions;