-- Practical NASA Data for Farmers Quiz
-- Real-world scenarios and applications that farmers can use immediately

-- Create Practical Farming with NASA Data Quiz
insert into public.quizzes (
   id,
   title,
   difficulty,
   nasa_topic,
   questions_count,
   attempts_allowed
) values ( 'practical-nasa-farming',
           'NASA Data কিভাবে ব্যবহার করবেন চাষাবাদে',
           'Easy',
           'Practical Applications',
           0,
           5 );

-- Practical NASA data questions for farmers
insert into public.quiz_questions (
   quiz_id,
   question,
   options,
   correct_answer,
   explanation,
   nasa_data_reference
) values ( 'practical-nasa-farming',
           'আপনার জমির ফসলের স্বাস্থ্য দেখার জন্য কোন NASA data ব্যবহার করবেন?',
           '["Temperature data", "NDVI (vegetation index)", "Wind speed", "Cloud cover"]',
           'NDVI (vegetation index)',
           'NDVI দিয়ে আপনি দেখতে পারবেন আপনার ফসল কতটা সুস্থ। সবুজ রঙ মানে ভালো ফসল, লাল রঙ মানে সমস্যা।',
           '{"practical_use": "ফসলের স্বাস্থ্য মনিটরিং", "data_source": "MODIS NDVI", "frequency": "প্রতি ৮ দিন"}' ),( 'practical-nasa-farming'
           ,
                                                                                                                       'কখন সেচ দিতে হবে তা জানার জন্য কোন NASA data দেখবেন?'
                                                                                                                       ,
                                                                                                                       '["Cloud pictures", "Soil moisture data (SMAP)", "Satellite photos", "Wind direction"]'
                                                                                                                       ,
                                                                                                                       'Soil moisture data (SMAP)'
                                                                                                                       ,
                                                                                                                       'NASA SMAP satellite মাটির আর্দ্রতা মাপে। কম আর্দ্রতা মানে সেচের প্রয়োজন, বেশি আর্দ্রতা মানে সেচ দরকার নেই।'
                                                                                                                       ,
                                                                                                                       '{"practical_use": "সেচের সময় নির্ধারণ", "data_source": "SMAP soil moisture", "update": "প্রতি ৩ দিন"}'
                                                                                                                       ),( 'practical-nasa-farming'
                                                                                                                       ,
                                                                                                                                                                                                                                'আগামী সপ্তাহে বৃষ্টি হবে কিনা জানতে কোন NASA service ব্যবহার করবেন?'
                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                '["NDVI data", "GPM precipitation forecast", "Temperature only", "Historical data"]'
                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                'GPM precipitation forecast'
                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                'NASA GPM satellite বৃষ্টিপাতের তথ্য দেয়। এটা দেখে আপনি জানতে পারবেন কবে বৃষ্টি হবে, তাই সার বা কীটনাশক স্প্রে করার সময় ঠিক করতে পারবেন।'
                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                '{"practical_use": "বৃষ্টির পূর্বাভাস", "data_source": "GPM satellite", "benefit": "স্প্রে/সার প্রয়োগের সময় নির্ধারণ"}'
                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                (
                                                                                                                                                                                                                                'practical-nasa-farming'
                                                                                                                                                                                                                                ,
                                                                                                                                                                                                                                                                                                                                                          'আপনার এলাকায় খরা আসছে কিনা বুঝবেন কীভাবে?'
                                                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                                                          '["শুধু তাপমাত্রা দেখে", "Soil moisture + precipitation data একসাথে", "শুধু বাতাসের গতি দেখে", "চাঁদের অবস্থান দেখে"]'
                                                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                                                          'Soil moisture + precipitation data একসাথে'
                                                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                                                          'খরা বুঝতে হলে দুটি জিনিস দেখতে হবে: মাটিতে পানি কম আছে কিনা (SMAP) এবং বৃষ্টি কম হচ্ছে কিনা (GPM)। দুটোই কম হলে খরা আসছে।'
                                                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                                                          '{"early_warning": "খরার আগাম সতর্কতা", "indicators": ["কম soil moisture", "কম precipitation"], "action": "সেচের ব্যবস্থা করা"}'
                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                                                          (
                                                                                                                                                                                                                                                                                                                                                          'practical-nasa-farming'
                                                                                                                                                                                                                                                                                                                                                          ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'ফসল কাটার সঠিক সময় জানতে কোন NASA data সবচেয়ে কাজে লাগে?'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '["Wind speed", "NDVI time series (সময়ের সাথে vegetation index)", "Cloud cover", "Air pressure"]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'NDVI time series (সময়ের সাথে vegetation index)'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'NDVI যখন সর্বোচ্চে পৌঁছে তারপর কমতে শুরু করে, তখনই ফসল কাটার সময়। এটা দেখে আপনি সঠিক সময়ে ফসল কাটতে পারবেন।'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '{"harvest_timing": "ফসল কাটার সময়", "method": "NDVI peak detection", "benefit": "সর্বোচ্চ ফলন পাওয়া"}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ;

-- Create Problem-Solution Scenarios Quiz
insert into public.quizzes (
   id,
   title,
   difficulty,
   nasa_topic,
   questions_count,
   attempts_allowed
) values ( 'farming-problems-nasa',
           'চাষাবাদের সমস্যা ও NASA সমাধান',
           'Medium',
           'Problem Solving',
           0,
           3 );

-- Problem-solving scenarios with NASA data
insert into public.quiz_questions (
   quiz_id,
   question,
   options,
   correct_answer,
   explanation,
   nasa_data_reference
) values ( 'farming-problems-nasa',
           'আপনার জমির একটা অংশে ফসল হলুদ হয়ে যাচ্ছে। NASA data দিয়ে কারণ খুঁজবেন কীভাবে?',
           '["শুধু weather data দেখবো", "NDVI map দেখে সেই এলাকা identify করবো তারপর soil moisture check করবো", "কিছুই করবো না", "শুধু temperature দেখবো"]'
           ,
           'NDVI map দেখে সেই এলাকা identify করবো তারপর soil moisture check করবো',
           'NDVI map এ হলুদ/লাল এলাকা দেখাবে কোথায় সমস্যা। তারপর soil moisture দেখে বুঝবেন পানির অভাব নাকি অন্য কিছু।',
           '{"problem": "ফসলের রঙ পরিবর্তন", "diagnosis": "NDVI mapping → soil moisture analysis", "solution": "targeted intervention"}'
           ),( 'farming-problems-nasa',
                                                                                                                                         'বীজ বপনের আগে মাটি প্রস্তুত কিনা জানতে কোন NASA data combination সবচেয়ে ভালো?'
                                                                                                                                         ,
                                                                                                                                         '["শুধু temperature", "Soil moisture + recent precipitation + temperature", "শুধু NDVI", "শুধু wind data"]'
                                                                                                                                         ,
                                                                                                                                         'Soil moisture + recent precipitation + temperature'
                                                                                                                                         ,
                                                                                                                                         'বীজ বপনের জন্য মাটিতে সঠিক পরিমাণ আর্দ্রতা (SMAP), সাম্প্রতিক বৃষ্টি (GPM), এবং উপযুক্ত তাপমাত্রা (POWER) - তিনটাই দরকার।'
                                                                                                                                         ,
                                                                                                                                         '{"land_preparation": "মাটি প্রস্তুতি", "parameters": ["soil_moisture", "precipitation", "temperature"], "timing": "optimal_planting_window"}'
                                                                                                                                         )
                                                                                                                                         ,
                                                                                                                                         (
                                                                                                                                         'farming-problems-nasa'
                                                                                                                                         ,
                                                                                                                                                                                                                                                                                        'আপনার এলাকায় পোকার আক্রমণ বেড়েছে। NASA data কীভাবে সাহায্য করতে পারে?'
                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                        '["NASA data পোকার সাথে সম্পর্কিত না", "Temperature ও humidity data দেখে পোকার breeding season predict করা", "শুধু satellite ছবি দেখা", "কিছুই করা যায় না"]'
                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                        'Temperature ও humidity data দেখে পোকার breeding season predict করা'
                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                        'NASA POWER data থেকে তাপমাত্রা ও আর্দ্রতা দেখে আপনি বুঝতে পারবেন কখন পোকার বংশবৃদ্ধি বেশি হয়। তখন আগে থেকেই প্রতিরোধ ব্যবস্থা নিতে পারবেন।'
                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                        '{"pest_management": "পোকামাকড় নিয়ন্ত্রণ", "predictors": ["temperature", "humidity"], "prevention": "early_warning_system"}'
                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                        (
                                                                                                                                                                                                                                                                                        'farming-problems-nasa'
                                                                                                                                                                                                                                                                                        ,
                                                                                                                                                                                                                                                                                                                                                                                                                       'সার দেওয়ার সবচেয়ে ভালো সময় জানতে কোন NASA data গুলো একসাথে দেখবেন?'
                                                                                                                                                                                                                                                                                                                                                                                                                       ,
                                                                                                                                                                                                                                                                                                                                                                                                                       '["শুধু NDVI", "Precipitation forecast + soil moisture + NDVI", "শুধু temperature", "শুধু cloud cover"]'
                                                                                                                                                                                                                                                                                                                                                                                                                       ,
                                                                                                                                                                                                                                                                                                                                                                                                                       'Precipitation forecast + soil moisture + NDVI'
                                                                                                                                                                                                                                                                                                                                                                                                                       ,
                                                                                                                                                                                                                                                                                                                                                                                                                       'সার দেওয়ার আগে দেখতে হবে: বৃষ্টি আছে কিনা (GPM), মাটিতে আর্দ্রতা আছে কিনা (SMAP), এবং গাছের বর্তমান অবস্থা (NDVI)। তিনটা ঠিক থাকলে সার দিন।'
                                                                                                                                                                                                                                                                                                                                                                                                                       ,
                                                                                                                                                                                                                                                                                                                                                                                                                       '{"fertilizer_timing": "সার প্রয়োগের সময়", "conditions": ["upcoming_rain", "adequate_soil_moisture", "plant_needs"], "efficiency": "maximum_uptake"}'
                                                                                                                                                                                                                                                                                                                                                                                                                       )
                                                                                                                                                                                                                                                                                                                                                                                                                       ,
                                                                                                                                                                                                                                                                                                                                                                                                                       (
                                                                                                                                                                                                                                                                                                                                                                                                                       'farming-problems-nasa'
                                                                                                                                                                                                                                                                                                                                                                                                                       ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               'নতুন এলাকায় চাষ শুরু করার আগে কোন NASA historical data দেখবেন?'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               '["শুধু গত মাসের data", "গত ৫-১০ বছরের precipitation, temperature, এবং NDVI patterns", "শুধু আজকের weather", "কোনো data দেখবো না"]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               'গত ৫-১০ বছরের precipitation, temperature, এবং NDVI patterns'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               'নতুন এলাকায় চাষের আগে সেখানের গত কয়েক বছরের আবহাওয়া, বৃষ্টিপাত, এবং vegetation patterns দেখে নিন। এতে বুঝবেন কোন ফসল ভালো হবে।'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               '{"site_assessment": "চাষের জমি মূল্যায়ন", "historical_analysis": "5-10 years", "crop_selection": "data_driven_decision"}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ;

-- Create Advanced Techniques Quiz
insert into public.quizzes (
   id,
   title,
   difficulty,
   nasa_topic,
   questions_count,
   attempts_allowed
) values ( 'advanced-nasa-techniques',
           'উন্নত NASA Data ব্যবহার কৌশল',
           'Hard',
           'Advanced Applications',
           0,
           3 );

-- Advanced NASA data techniques
insert into public.quiz_questions (
   quiz_id,
   question,
   options,
   correct_answer,
   explanation,
   nasa_data_reference
) values ( 'advanced-nasa-techniques',
           'বিভিন্ন ফসলের জন্য আলাদা NDVI threshold কেন দরকার?',
           '["সব ফসলের জন্য একই threshold", "প্রতিটি ফসলের growth pattern ও leaf structure আলাদা", "NASA data একই সবার জন্য", "কোনো threshold দরকার নেই"]'
           ,
           'প্রতিটি ফসলের growth pattern ও leaf structure আলাদা',
           'ধান, গম, ভুট্টা - প্রতিটি ফসলের পাতার গঠন আলাদা, বৃদ্ধির হার আলাদা। তাই NDVI value interpret করার সময় ফসল অনুযায়ী আলাদা standard ব্যবহার করতে হয়।'
           ,
           '{"crop_specific": "ফসল-নির্দিষ্ট analysis", "factors": ["leaf_area", "growth_rate", "canopy_structure"], "application": "precision_monitoring"}'
           ),( 'advanced-nasa-techniques',
                                                                                                                                                             'Variable Rate Application এর জন্য NASA data কীভাবে ব্যবহার করবেন?'
                                                                                                                                                             ,
                                                                                                                                                             '["সব জমিতে সমান সার দেবো", "NDVI map অনুযায়ে জমির বিভিন্ন অংশে আলাদা পরিমাণ সার দেবো", "শুধু অনুমান করে সার দেবো", "কোনো map ব্যবহার করবো না"]'
                                                                                                                                                             ,
                                                                                                                                                             'NDVI map অনুযায়ী জমির বিভিন্ন অংশে আলাদা পরিমাণ সার দেবো'
                                                                                                                                                             ,
                                                                                                                                                             'NDVI map দেখে জানা যায় জমির কোন অংশে গাছ কম সুস্থ (কম NDVI)। সেখানে বেশি সার, যেখানে গাছ ভালো (বেশি NDVI) সেখানে কম সার দিলে খরচ কম, ফলন বেশি।'
                                                                                                                                                             ,
                                                                                                                                                             '{"precision_agriculture": "নির্দিষ্ট কৃষি", "technique": "variable_rate_fertilization", "benefit": "cost_reduction + yield_optimization"}'
                                                                                                                                                             )
                                                                                                                                                             ,
                                                                                                                                                             (
                                                                                                                                                             'advanced-nasa-techniques'
                                                                                                                                                             ,
                                                                                                                                                                                                                                                                                                         'ফসলের stress early detection এর জন্য কোন approach সবচেয়ে কার্যকর?'
                                                                                                                                                                                                                                                                                                         ,
                                                                                                                                                                                                                                                                                                         '["একবার NDVI দেখলেই হবে", "NDVI + soil moisture + weather data এর combination এবং time series analysis", "শুধু চোখে দেখা", "শুধু temperature দেখা"]'
                                                                                                                                                                                                                                                                                                         ,
                                                                                                                                                                                                                                                                                                         'NDVI + soil moisture + weather data এর combination এবং time series analysis'
                                                                                                                                                                                                                                                                                                         ,
                                                                                                                                                                                                                                                                                                         'Early stress detection এর জন্য শুধু এক দিনের data নয়, বরং কয়েক সপ্তাহের NDVI trend, soil moisture pattern, এবং weather condition একসাথে analyze করতে হয়।'
                                                                                                                                                                                                                                                                                                         ,
                                                                                                                                                                                                                                                                                                         '{"early_detection": "আগাম সমস্যা চিহ্নিতকরণ", "multi_parameter": "NDVI+moisture+weather", "temporal_analysis": "trend_monitoring"}'
                                                                                                                                                                                                                                                                                                         )
                                                                                                                                                                                                                                                                                                         ,
                                                                                                                                                                                                                                                                                                         (
                                                                                                                                                                                                                                                                                                         'advanced-nasa-techniques'
                                                                                                                                                                                                                                                                                                         ,
                                                                                                                                                                                                                                                                                                                                                                                                                                              'Climate change adaptation এর জন্য NASA long-term data কীভাবে ব্যবহার করবেন?'
                                                                                                                                                                                                                                                                                                                                                                                                                                              ,
                                                                                                                                                                                                                                                                                                                                                                                                                                              '["শুধু এ বছরের data দেখবো", "২০+ বছরের precipitation ও temperature trends analyze করে crop selection ও farming practices adjust করবো", "কোনো planning করবো না", "শুধু tradition follow করবো"]'
                                                                                                                                                                                                                                                                                                                                                                                                                                              ,
                                                                                                                                                                                                                                                                                                                                                                                                                                              '২০+ বছরের precipitation ও temperature trends analyze করে crop selection ও farming practices adjust করবো'
                                                                                                                                                                                                                                                                                                                                                                                                                                              ,
                                                                                                                                                                                                                                                                                                                                                                                                                                              'Climate change এর সাথে adapt করতে হলে NASA এর ২০+ বছরের data দেখে বুঝতে হবে আবহাওয়া কীভাবে পরিবর্তন হচ্ছে। তারপর সেই অনুযায়ী ফসল ও চাষ পদ্ধতি পরিবর্তন করতে হবে।'
                                                                                                                                                                                                                                                                                                                                                                                                                                              ,
                                                                                                                                                                                                                                                                                                                                                                                                                                              '{"climate_adaptation": "জলবায়ু অভিযোজন", "long_term_analysis": "20+ years", "strategy": "adaptive_farming_practices"}'
                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                              ,
                                                                                                                                                                                                                                                                                                                                                                                                                                              (
                                                                                                                                                                                                                                                                                                                                                                                                                                              'advanced-nasa-techniques'
                                                                                                                                                                                                                                                                                                                                                                                                                                              ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       'Precision irrigation এর জন্য NASA data integration কীভাবে করবেন?'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       '["শুধু একটা sensor যথেষ্ট", "SMAP soil moisture + GPM precipitation + ET data + field sensors এর combination", "শুধু manual checking", "fixed schedule অনুসরণ"]'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       'SMAP soil moisture + GPM precipitation + ET data + field sensors এর combination'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       'আধুনিক precision irrigation এ NASA satellite data (soil moisture, precipitation, evapotranspiration) এর সাথে মাঠের sensor data মিলিয়ে automated irrigation system তৈরি করা যায়।'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       '{"precision_irrigation": "নির্ভুল সেচ ব্যবস্থা", "data_fusion": "satellite+ground_sensors", "automation": "smart_irrigation_system"}'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ;

-- Update question counts for all new quizzes
update public.quizzes
   set
   questions_count = (
      select count(*)
        from public.quiz_questions
       where quiz_id = 'practical-nasa-farming'
   )
 where id = 'practical-nasa-farming';

update public.quizzes
   set
   questions_count = (
      select count(*)
        from public.quiz_questions
       where quiz_id = 'farming-problems-nasa'
   )
 where id = 'farming-problems-nasa';

update public.quizzes
   set
   questions_count = (
      select count(*)
        from public.quiz_questions
       where quiz_id = 'advanced-nasa-techniques'
   )
 where id = 'advanced-nasa-techniques';

-- Summary
select 'Practical NASA farming quizzes created!' as result,
       (
          select count(*)
            from public.quizzes
           where id like '%nasa%'
              or id like '%farming%'
       ) as total_quizzes,
       (
          select count(*)
            from public.quiz_questions
           where quiz_id like '%nasa%'
              or quiz_id like '%farming%'
       ) as total_questions;