// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Accept legacy/alternate env names for flexibility
const ENV_URL = (import.meta.env.VITE_SUPABASE_URL as string) || '';
const ENV_PROJECT_ID = (import.meta.env.VITE_SUPABASE_PROJECT_ID as string) || '';
const ENV_ANON = (import.meta.env.VITE_SUPABASE_ANON_KEY as string) || '';
const ENV_PUBLISHABLE = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string) || '';

const SUPABASE_URL = ENV_URL || (ENV_PROJECT_ID ? `https://${ENV_PROJECT_ID}.supabase.co` : '');
const SUPABASE_KEY = ENV_ANON || ENV_PUBLISHABLE;

// Import the supabase client like this:
// import { supabase } from "/@/integrations/supabase/client";

let _client: SupabaseClient<Database> | null = null;

function create(): SupabaseClient<Database> {
  if (!SUPABASE_URL || !SUPABASE_KEY) {
    const msg = '[Supabase] Missing URL/key. Provide VITE_SUPABASE_URL (or VITE_SUPABASE_PROJECT_ID) and VITE_SUPABASE_ANON_KEY (or VITE_SUPABASE_PUBLISHABLE_KEY) in .env.';
    // Log for visibility, but don't throw yet to avoid breaking static imports
    console.error(msg);
    throw new Error(msg);
  }
  return createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_target, prop) {
    if (!_client) {
      _client = create();
    }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const anyClient = _client as any;
    return anyClient[prop as keyof typeof anyClient];
  },
});